# Generated by Django 2.0.6 on 2018-07-09 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refuge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCharacterist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=200)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refuge.Pet')),
            ],
            options={
                'verbose_name': 'PetCharacterist',
                'verbose_name_plural': 'PetCharacterists',
            },
        ),
    ]
