# Generated by Django 2.0.6 on 2018-07-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refuge', '0003_auto_20180710_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petcharacteristic',
            options={'verbose_name': 'PetCharacteristic', 'verbose_name_plural': 'PetCharacteristics'},
        ),
    ]
