# Generated by Django 2.0.6 on 2018-07-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='number_active_sessions',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
