# Generated by Django 2.0.6 on 2018-07-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180713_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwebsocketsession',
            old_name='session_token',
            new_name='token',
        ),
    ]
