# Generated by Django 2.0.6 on 2018-07-17 16:59

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_userwebsocketsession_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwebsocketsession',
            name='port',
            field=models.PositiveIntegerField(default=usuario.models.generate_port),
        ),
        migrations.AlterField(
            model_name='userwebsocketsession',
            name='token',
            field=models.CharField(default=usuario.models.generate_token, max_length=50, unique=True),
        ),
    ]
